version: '3.4'

services:

  starbux-db:
    container_name: Starbux_DB
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_USER: docker
      MYSQL_PASSWORD: Test123
      MYSQL_DATABASE: starbux
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3318
    ports:
      - 3318:3318
    expose:
      - 3318
    networks:
      - starbux-network
  
  starbux-service:
    container_name: Starbux_Service
    image: jeremiasrg/starbux:1.0.0
    ports:
      - 8100:8100
    depends_on:
      - starbux-db
    restart: on-failure
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://starbux-db:3318/starbux?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2&autoReconnect=true
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: Test123
      SPRING.FLYWAY.URL: jdbc:mysql://starbux-db:3318/starbux?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2&autoReconnect=true
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: Test123
    networks:
      - starbux-network
      
networks:
  starbux-network:
    driver: bridge