server:
  port: 8100
spring:  application:    name: starbux
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starbux?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
  jackson:    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/starbux?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    user: root